Rabbit:
  Host: localhost # for docker to use in mac put: host.docker.internal
  Port: 5672
  User: guest
  Pass: guest
  ExchangeName: "tasks-exchange"
  RoutingKey: "tasks-routing-key"

Healer:
  RetryTimes: 100
  RetryDelay: 2  # in seconds
  PingInterval: 1 # in seconds

Producer:
  Interval: 3 # in seconds
  NumberOfTasks: 2